#!/bin/bash

## Emacs
alias et='emacsclient -t'
alias en='emacs -nw --no-init-file '
e() { emacs "$@" & }
alias makeEmacsDir='[[ -d /tmp/emacs$(id -u) ]] || mkdir /tmp/emacs$(id -u)'

## Evince
ev() { evince "$@" & }

## Vidyo
alias resetVidyo='killall VidyoDesktop; VidyoDesktop&'

## Misc
rl() {
    cd $(dirname "$@")
    echo $PWD/$(basename "$@")
    cd - &>/dev/null
}
alias ll='ls -rtlh '
alias l='ls -lh '
